export function work ($containerGeneral){
    const content_all = document.createElement("section");
    content_all.className = ("content_all");
    $containerGeneral.appendChild(content_all);
    const work_area = document.createElement("div");
    work_area.className ='work_area';
    work_area.setAttribute("id", "work");
    content_all.appendChild(work_area);
    const fondo_header =document.createElement("div");
    fondo_header.className = "fn_header"
    work_area.appendChild(fondo_header)
    const decoration = document.createElement("img");
    decoration.src='images/bt_home2.png';
    decoration.className ="bt_decoration";
    work_area.appendChild(decoration);
    const decoration2 = document.createElement("img");
    decoration2.src='images/bt_home2.png';
    decoration2.setAttribute("id", "dec2");
    work_area.appendChild(decoration2);
    const decoration3 = document.createElement("img");
    decoration3.src='images/Group.png';
    decoration3.setAttribute("id", "dec3");
    work_area.appendChild(decoration3);
    const decoration4 = document.createElement("img");
    decoration4.src='images/bt_home2.png';
    decoration4.setAttribute("id", "dec4");
    work_area.appendChild(decoration4);
    const decoration5 = document.createElement("img");
    decoration5.src='images/bt_home2.png';
    decoration5.setAttribute("id", "dec5");
    work_area.appendChild(decoration5);
    const decoration6 = document.createElement("img");
    decoration6.src='images/Group.png';
    decoration6.setAttribute("id", "dec6");
    work_area.appendChild(decoration6);
    const decoration7 = document.createElement("img");
    decoration7.src='images/Group.png';
    decoration7.setAttribute("id", "dec7");
    work_area.appendChild(decoration7);
    const decoration8 = document.createElement("img");
    decoration8.src='images/bt_home2.png';
    decoration8.setAttribute("id", "dec8");
    work_area.appendChild(decoration8);
    const decoration9 = document.createElement("img");
    decoration9.src='images/Group.png';
    decoration9.setAttribute("id", "dec9");
    work_area.appendChild(decoration9);
    const decoration10 = document.createElement("img");
    decoration10.src='images/bt_home2.png';
    decoration10.setAttribute("id", "dec10");
    work_area.appendChild(decoration10);
    const decoration11 = document.createElement("img");
    decoration11.src='images/Group.png';
    decoration11.setAttribute("id", "dec11");
    work_area.appendChild(decoration11);
    const decoration12 = document.createElement("img");
    decoration12.src='images/bt_home2.png';
    decoration12.setAttribute("id", "dec12");
    work_area.appendChild(decoration12);
    const decoration13 = document.createElement("img");
    decoration13.src='images/bt_home2.png';
    decoration13.setAttribute("id", "dec13");
    work_area.appendChild(decoration13);
    const decoration14 = document.createElement("img");
    decoration14.src='images/Group.png';
    decoration14.setAttribute("id", "dec14");
    work_area.appendChild(decoration14);
    const all_proyects =document.createElement('p');
    all_proyects.className=" all_proyects";
    all_proyects.textContent="Mis proyectos";
    content_all.appendChild( all_proyects);
    const fondo_work = document.createElement("img");
    fondo_work.src='images/fondo_work.png';
    fondo_work.className ="fondo_work";
    work_area.appendChild(fondo_work);
    const decoration15 = document.createElement("img");
    decoration15.src='images/Group.png';
    decoration15.setAttribute("id", "dec15");
    content_all.appendChild(decoration15);
    const circle_work = document.createElement('div');
    circle_work.className= 'circle_work';
    content_all.appendChild(circle_work);
}